apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ne1x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ne1x
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ne1x
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ne1x
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ne1x
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-chko-tenant/rhtap-demo-app/hacbs-test-project-ne1x@sha256:61a18d984e95f97f528a96df3869ed94a4d36db7077fba7cf5d31d3b447a7ae9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
