apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ne1x
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-chko-tenant/rhtap-demo-app/hacbs-test-project-ne1x@sha256:61a18d984e95f97f528a96df3869ed94a4d36db7077fba7cf5d31d3b447a7ae9
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
