apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ne1x
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-chko-tenant/rhtap-demo-app/hacbs-test-project-ne1x@sha256:efab139b0028367052519d7f5e2ccf514a48ddfea09bde610bc719e94b68610d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
